### ISSUE TITLE
A possible improvement

### ISSUE THREAD

**Issue by DaveKim3872** [axipo/pdfTranslator#2]
你好，
现发现如果翻译段落比较长，翻译结果浮窗既无法完全显示也无法滚动显示下面的内容。可否在这方面做些适配，谢谢。

Hi there, 
I found that if the translation paragraph is relatively long, the translation result floating window can neither fully display nor scroll the following content. Can you make some adjustments in this respect? 
Thank you.

**Comment by axipo** [comment]
> 你好，
> 现发现如果翻译段落比较长，翻译结果浮窗既无法完全显示也无法滚动显示下面的内容。可否在这方面做些适配，谢谢。
> 
> Hi there,
> I found that if the translation paragraph is relatively long, the translation result floating window can neither fully display nor scroll the following content. Can you make some adjustments in this respect?
> Thank you.

fixed, [here is the new releases](https://github.com/axipo/pdfTranslator/releases/tag/v0.3.2)

thx for your suggestion
