### ISSUE TITLE
Translation becomes garbled when context includes ''%"

### ISSUE THREAD

**Issue by 0064Unknown** [axipo/pdfTranslator#3]
当截取的内容中含有“%”符号时，显示的翻译结果会变得杂乱
![Screenshot_2019-11-07 Principles of Corporate Finance 12th Edition by Richard Brealey pdf](https://user-images.githubusercontent.com/43371529/68363600-6cb03280-0166-11ea-9341-804113de55a4.png)

**Comment by 0064Unknown** [comment]
![Screenshot_2019-11-07 Principles of Corporate Finance 12th Edition by Richard Brealey pdf(1)](https://user-images.githubusercontent.com/43371529/68363690-b731af00-0166-11ea-87ef-8993aa994d3c.png)

**Comment by axipo** [comment]
感谢反馈，已经在0.3.3版本中修复
